#!/usr/bin/env python

from JetCalibration.ApplyCalibrationFactors.BuildCalibrationVPSet import BuildCalibrationVPSet

filenamesAndOutputNames = [
  ("/hdfs/user/sb17498/CMS_Phase_2/jetMETStudies/CalibrationFactors/Calibration_Trees_Calibration_PU200_Puppi_NoZeroPtJets_FinerGranularity_MatchAK4GenJetWithAK4JetFromPfCandidates.root", "Calibration_Trees_Calibration_PU200_Puppi_NoZeroPtJets_FinerGranularity_MatchAK4GenJetWithAK4JetFromPfCandidates.pickle"),
  ("/hdfs/user/sb17498/CMS_Phase_2/jetMETStudies/CalibrationFactors/Calibration_Trees_Calibration_PU200_Puppi_NoZeroPtJets_FinerGranularity_MatchAK4GenJetWithAK4JetFromPfClusters.root", "Calibration_Trees_Calibration_PU200_Puppi_NoZeroPtJets_FinerGranularity_MatchAK4GenJetWithAK4JetFromPfClusters.pickle"),
  ("/hdfs/user/sb17498/CMS_Phase_2/jetMETStudies/CalibrationFactors/Calibration_Trees_Calibration_PU200_Puppi_NoZeroPtJets_FinerGranularity_MatchAK4GenJetWithPhase1L1TJetFromPfCandidates.root", "Calibration_Trees_Calibration_PU200_Puppi_NoZeroPtJets_FinerGranularity_MatchAK4GenJetWithPhase1L1TJetFromPfCandidates.pickle"),
  ("/hdfs/user/sb17498/CMS_Phase_2/jetMETStudies/CalibrationFactors/Calibration_Trees_Calibration_PU200_Puppi_NoZeroPtJets_FinerGranularity_MatchAK4GenJetWithPhase1L1TJetFromPfClusters.root", "Calibration_Trees_Calibration_PU200_Puppi_NoZeroPtJets_FinerGranularity_MatchAK4GenJetWithPhase1L1TJetFromPfClusters.pickle"),
  ("/hdfs/user/sb17498/CMS_Phase_2/jetMETStudies/CalibrationFactors/Calibration_Trees_Calibration_PU200_Puppi_NoZeroPtJets_MatchAK4GenJetWithAK4JetFromPfCandidates.root", "Calibration_Trees_Calibration_PU200_Puppi_NoZeroPtJets_MatchAK4GenJetWithAK4JetFromPfCandidates.pickle"),
  ("/hdfs/user/sb17498/CMS_Phase_2/jetMETStudies/CalibrationFactors/Calibration_Trees_Calibration_PU200_Puppi_NoZeroPtJets_MatchAK4GenJetWithPhase1L1TJetFromPfCandidates.root", "Calibration_Trees_Calibration_PU200_Puppi_NoZeroPtJets_MatchAK4GenJetWithPhase1L1TJetFromPfCandidates.pickle"),
  ("/hdfs/user/sb17498/CMS_Phase_2/jetMETStudies/CalibrationFactors/Calibration_Trees_Calibration_PU200_Puppi_NoZeroPtJets_MatchAK4GenJetWithPhase1L1TJetFromPfClusters.root", "Calibration_Trees_Calibration_PU200_Puppi_NoZeroPtJets_MatchAK4GenJetWithPhase1L1TJetFromPfClusters.pickle"),
  ("/hdfs/user/sb17498/CMS_Phase_2/jetMETStudies/CalibrationFactors/Calibration_Trees_Calibration_PUSubtractionBranch_PU200_Puppi_NoZeroPtJets_MatchAK4GenJetWithAK4JetFromPfCandidates.root", "Calibration_Trees_Calibration_PUSubtractionBranch_PU200_Puppi_NoZeroPtJets_MatchAK4GenJetWithAK4JetFromPfCandidates.pickle"),
  ("/hdfs/user/sb17498/CMS_Phase_2/jetMETStudies/CalibrationFactors/Calibration_Trees_Calibration_PUSubtractionBranch_PU200_Puppi_NoZeroPtJets_MatchAK4GenJetWithAK4JetFromPfClusters.root", "Calibration_Trees_Calibration_PUSubtractionBranch_PU200_Puppi_NoZeroPtJets_MatchAK4GenJetWithAK4JetFromPfClusters.pickle"),
  ("/hdfs/user/sb17498/CMS_Phase_2/jetMETStudies/CalibrationFactors/Calibration_Trees_Calibration_PUSubtractionBranch_PU200_Puppi_NoZeroPtJets_MatchAK4GenJetWithPhase1L1TJetFromPfCandidates.root", "Calibration_Trees_Calibration_PUSubtractionBranch_PU200_Puppi_NoZeroPtJets_MatchAK4GenJetWithPhase1L1TJetFromPfCandidates.pickle"),
  ("/hdfs/user/sb17498/CMS_Phase_2/jetMETStudies/CalibrationFactors/Calibration_Trees_Calibration_PUSubtractionBranch_PU200_Puppi_NoZeroPtJets_MatchAK4GenJetWithPhase1L1TJetFromPfClusters.root", "Calibration_Trees_Calibration_PUSubtractionBranch_PU200_Puppi_NoZeroPtJets_MatchAK4GenJetWithPhase1L1TJetFromPfClusters.pickle"),
]

etaBinning = [0, 0.435, 0.783, 1.131, 1.305, 1.479, 1.653, 1.830, 1.930,
            2.043, 2.172, 2.322, 2.5, 2.964, 3.489, 4.191, 5.191] 

for filenames in filenamesAndOutputNames: 
  BuildCalibrationVPSet(filenames[0], etaBinning, filenames[1])