Universe = vanilla
job = MinBias_TuneCUETP8M1_14TeV_GenInfo
cmd = L1TJetConvolutionCurves/MatchGenJetWithL1Objects/test/runCMSSWWrapper.sh
args= -j $(job) -c $(cluster) -p $(process) -i L1TJetConvolutionCurves/MatchGenJetWithL1Objects/python/SaveGenLevelInfo_cfg.py -d MinBias_TuneCUETP8M1_14TeV_GenInfo -s source_MinBias_TuneCUETP8M1_14TeV_splitted -b convolutionCurves_BarrelJetsOnly_crossMatch_CMSSW_9_3_0
# Better not to put logs in the same folder, as they are plenty
output = /storage/sb17498/logs/CMSSW/$(job)_$(cluster).$(process).out
error = /storage/sb17498/logs/CMSSW/$(job)_$(cluster).$(process).err
log = /storage/sb17498/logs/CMSSW/$(job)_$(cluster).$(process).log
should_transfer_files = YES
when_to_transfer_output = ON_EXIT_OR_EVICT
use_x509userproxy = true

requirements= Machine=!="hd-38-02.dice.priv"
request_cpus = 1
request_memory = 1000
request_disk = 1000000

queue 200