Universe = vanilla
job = muonMatching_Test
cmd = L1TJetConvolutionCurves/MatchGenJetWithL1Objects/test/runCMSSWWrapper.sh
args= -j $(job) -c $(cluster) -p $(process) -s HardQCD_PtBinned_10_30_GeV
# Better not to put logs in the same folder, as they are plenty
output = /storage/sb17498/logs/heppy/$(job)_$(cluster).$(process).out
error = /storage/sb17498/logs/heppy/$(job)_$(cluster).$(process).err
log = /storage/sb17498/logs/heppy/$(job)_$(cluster).$(process).log
should_transfer_files = YES
when_to_transfer_output = ON_EXIT_OR_EVICT
use_x509userproxy = true

requirements= Machine=!="hd-38-02.dice.priv"
request_cpus = 1
request_memory = 1000
request_disk = 1000000